# Generated by Django 5.1.15 on 2026-03-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Zdjęcie profilowe')),
                ('content', models.TextField(verbose_name='Treść sekcji O mnie')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'O mnie',
                'verbose_name_plural': 'O mnie',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=300, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytano')),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Kategoria portfolio',
                'verbose_name_plural': 'Kategorie portfolio',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fotograf', max_length=200, verbose_name='Tytuł strony')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Podtytuł / hasło')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Zdjęcie główne (hero)')),
                ('info_content', models.TextField(verbose_name='Treść sekcji Informacje')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informacje o stronie',
                'verbose_name_plural': 'Informacje o stronie',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Zdjęcie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Wyróżnione (na stronie głównej)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='portfolio.portfoliocategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Zdjęcie portfolio',
                'verbose_name_plural': 'Zdjęcia portfolio',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
