# Generated by Django 5.1.15 on 2026-03-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Zalecana wysokość: 40–50px. Jeśli nie wgrasz logo, wyświetli się tekst.', null=True, upload_to='logo/', verbose_name='Logo (w nawigacji)'),
        ),
    ]
